# Generated by Django 5.2.6 on 2025-09-21 20:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_options_schedule_homework_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='homework',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='homework_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='homework_file',
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст задания')),
                ('file', models.FileField(blank=True, null=True, upload_to='homework/%Y/%m/%d/', verbose_name='Файл задания')),
                ('assigned_date', models.DateField(default=datetime.date.today, verbose_name='Дата задания')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок сдачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кем задано')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_assignments', to='schedule.schedule')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ['-assigned_date'],
            },
        ),
    ]
