# Generated by Django 5.2.6 on 2025-09-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_teachergroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherGroup',
        ),
    ]
