# Generated by Django 5.2.6 on 2025-09-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_delete_teachergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='teacher_id',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер студенческого'),
        ),
    ]
