# Generated by Django 5.2.6 on 2025-09-28 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news'),
        ('schedule', '0006_schedule_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.subject', verbose_name='Предмет'),
        ),
    ]
