# Generated by Django 5.2.6 on 2025-10-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_homework_group_homework_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='faculty',
            field=models.CharField(max_length=100, null=True, verbose_name='Факультет'),
        ),
    ]
