# Generated by Django 5.2.6 on 2025-10-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_schedule_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='teacher_id',
            field=models.CharField(max_length=50, null=True, verbose_name='ID Преподавателя'),
        ),
    ]
