# Generated by Django 5.2.6 on 2025-10-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_alter_schedule_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('понедельник', 'Понедельник'), ('вторник', 'Вторник'), ('среда', 'Среда'), ('четверг', 'Четверг'), ('пятница', 'Пятница'), ('суббота', 'Суббота')], max_length=15, verbose_name='День недели'),
        ),
    ]
